sudo: true
dist: trusty
services:
  - docker

#language: haskell

before_install:
#  - ./.travis/install-dependencies.sh  
  - docker build -t bionitio-haskell .

script:
#  - ./functional_tests/bionitio-test.sh -p ~/.local/bin/bionitio-hs -d functional_tests/test_data
#  - ./.travis/unit-test.sh

  # Both of these same tests, in Docker
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-haskell
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-haskell -p bionitio-hs -d /bionitio/functional_tests/test_data

