sudo: true
dist: trusty
services:
  - docker

before_install:
  - docker build -t bionitio-haskell .

script:
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-haskell
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-haskell -p bioniti -d /bionitio/functional_tests/test_data -v
